servertemplates:
  - name: hj-sptemplate1
    enclosuregroup: DCA-SolCenter-EG
    serverhardwaretype: "SY 480 Gen9 3"
    connections:
      - id: 1
        name: nic1
        network: TE-Testing-300

  - name: hj-sptemplate2
    enclosuregroup: DCA-SolCenter-EG
    serverhardwaretype: "SY 480 Gen9 1"


networks: 
  - name: hj-test1
    vlanId: 671
  - name: hj-test2
    vlanId: 672

    